### ISSUE TITLE
AIS Decoder returns 404

### ISSUE THREAD

**Issue by st599** [seandepagnier/rtlsdr_pi#12]
`wget http://www.aishub.net/downloads/aisdecoder.tar.gz`

Returns:

`Resolving www.aishub.net (www.aishub.net)... 144.76.105.244
Connecting to www.aishub.net (www.aishub.net)|144.76.105.244|:80... connected.
HTTP request sent, awaiting response... 404 Not Found`

Same thing happens from the webpage with the download page - aisdecoder is not listed:
[http://www.aishub.net/downloads/](http://www.aishub.net/downloads/)

**Comment by seandepagnier** [comment]
could you use rtl_ais instead?

**Comment by rgleason** [comment]
This is the exact same line that caused trouble earlier with Windows.
It had to be commented out so that the plugin would work.
Since the download uses my repos right now for Windows it is not a problem, but doesn't it make sense to have this a conditional user Option that is off to begin with, and that will be hidden if rtlais is not available?

**Comment by rgleason** [comment]
Sean, 
Or perhaps it is simpler have two versions, one that wraps in and includes  rtlais and one that does not?

**Comment by st599** [comment]
I can use rtl-ais.
How does one integrate this with OpenCPN?
Is it possible to autocalibrate the PPM value?

**Comment by seandepagnier** [comment]
rtl-ais is already supported by the plugin.  aisdecoder is still supported but old.

I don't know of a way to autocalibrate ppm besides what the plugin does. It is an inefficient way and you need plenty of traffic.
